// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFIVKSLYdVHa5T9fDyUFK0zTmZS7_jnSM',
    appId: '1:409345998112:web:3dfb542fdf12125f6dab45',
    messagingSenderId: '409345998112',
    projectId: 'todo-list-with-flutter',
    authDomain: 'todo-list-with-flutter.firebaseapp.com',
    storageBucket: 'todo-list-with-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALpy2vHYNq2U4ohe8xXh4PxgcK-Angc1Y',
    appId: '1:409345998112:android:948f9fdb86f6bb5c6dab45',
    messagingSenderId: '409345998112',
    projectId: 'todo-list-with-flutter',
    storageBucket: 'todo-list-with-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYVo9ZnLW4_4mmPItfvRX-q_sVS_Uh7HA',
    appId: '1:409345998112:ios:7332bf7680906b136dab45',
    messagingSenderId: '409345998112',
    projectId: 'todo-list-with-flutter',
    storageBucket: 'todo-list-with-flutter.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYVo9ZnLW4_4mmPItfvRX-q_sVS_Uh7HA',
    appId: '1:409345998112:ios:7332bf7680906b136dab45',
    messagingSenderId: '409345998112',
    projectId: 'todo-list-with-flutter',
    storageBucket: 'todo-list-with-flutter.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFIVKSLYdVHa5T9fDyUFK0zTmZS7_jnSM',
    appId: '1:409345998112:web:effd113e17447bb16dab45',
    messagingSenderId: '409345998112',
    projectId: 'todo-list-with-flutter',
    authDomain: 'todo-list-with-flutter.firebaseapp.com',
    storageBucket: 'todo-list-with-flutter.appspot.com',
  );
}
